name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build