#name of workflow
name: Android Build

#when to run
#trigger on every pull request and on push to the master branch
on:
  pull_request:
    pull:
      branches:
        - master



#task to be run

jobs:
  build:

    runs_on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble